//! Every art, audio and font asset the game uses, imported in one place.
//!
//! The PNG and WAV files are generated by the scripts in `tools/asset_gen/`
//! (see `assets/README.md`).  agb converts them to GBA-native formats at
//! compile time, so the ROM contains no PNG/WAV data — only raw tiles,
//! palettes and PCM samples.

use agb::display::font::Font;
use agb::sound::mixer::SoundData;
use agb::{include_aseprite, include_background_gfx, include_font, include_wav};

// ---------------------------------------------------------------------------
// Sprites.  Each PNG is a horizontal strip; the number before the path is the
// frame width, so e.g. `16 "...hero_topdown.png"` slices it into 16px frames.
// ---------------------------------------------------------------------------
include_aseprite!(
    mod sprites,
    16 "assets/sprites/hero_topdown.png",
    16 "assets/sprites/hero_platform.png",
    16 "assets/sprites/npcs.png",
    16 "assets/sprites/enemy.png",
    16 "assets/sprites/flag.png",
    8 "assets/sprites/ui.png",
);

/// Glitch bug: frames 0-1 walking, 2 squashed.
pub use sprites::ENEMY;
/// Checkered goal flag (16x32), two waving frames.
pub use sprites::FLAG;
/// Platformer hero: 0 idle, 1-2 run, 3 jump, 4 hurt.
pub use sprites::HERO_PLATFORM;
/// Overworld hero: frames 0-2 facing down, 3-5 up, 6-8 right (idle, step, step).
pub use sprites::HERO_TOPDOWN;
/// The five challengers, in path order: kid, old man, woman, ranger, robot.
pub use sprites::NPCS;
/// 8x8 UI icons: 0 full heart, 1 empty heart, 2 alert "!".
pub use sprites::UI;

// ---------------------------------------------------------------------------
// Background tile sheets.  Combined in one macro call so their palettes are
// packed together; `PALETTES` is loaded once at startup in main().
// ---------------------------------------------------------------------------
include_background_gfx!(
    mod backgrounds,
    title => deduplicate "assets/backgrounds/title.png",
    topdown => "assets/backgrounds/topdown_tiles.png",
    platform => "assets/backgrounds/platform_tiles.png",
    panel => "assets/backgrounds/ui_panel.png",
);

pub use backgrounds::{PALETTES, panel, platform, title, topdown};

/// Background palette slot reserved for font rendering (palettes from
/// `PALETTES` are loaded starting at slot 0; 15 is safely out of their way).
pub const TEXT_PALETTE: u8 = 15;

// ---------------------------------------------------------------------------
// Font: "Pixelated" by codeman38 (see assets/fonts/license.txt).
// ---------------------------------------------------------------------------
pub static FONT: Font = include_font!("assets/fonts/pixelated.ttf", 8);

// ---------------------------------------------------------------------------
// Audio.  All mono PCM at 18157 Hz, matching the mixer frequency.
// ---------------------------------------------------------------------------
pub static SFX_JUMP: SoundData = include_wav!("assets/sounds/jump.wav");
pub static SFX_STOMP: SoundData = include_wav!("assets/sounds/stomp.wav");
pub static SFX_HURT: SoundData = include_wav!("assets/sounds/hurt.wav");
pub static SFX_LOSE_LIFE: SoundData = include_wav!("assets/sounds/lose_life.wav");
pub static SFX_WIN_LEVEL: SoundData = include_wav!("assets/sounds/win_level.wav");
pub static SFX_TALK_BLIP: SoundData = include_wav!("assets/sounds/talk_blip.wav");
pub static SFX_MENU_MOVE: SoundData = include_wav!("assets/sounds/menu_move.wav");
pub static SFX_MENU_SELECT: SoundData = include_wav!("assets/sounds/menu_select.wav");
pub static SFX_SAVE_CHIME: SoundData = include_wav!("assets/sounds/save_chime.wav");

pub static MUSIC_TITLE: SoundData = include_wav!("assets/sounds/music_title.wav");
pub static MUSIC_OVERWORLD: SoundData = include_wav!("assets/sounds/music_overworld.wav");
pub static MUSIC_PLATFORM: SoundData = include_wav!("assets/sounds/music_platform.wav");
